name: Deploy to Webserver

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - name: Install Dependencies & Build
      run: |
        npm ci
        npm run build
    
    - name: Deploy to webhost via SSH/Rsync
      uses: burnett01/rsync-deployments@v9
      with:
        path: ./build/
        remote_path: ${{ secrets.DEPLOY_DIRECTORY }}
        remote_host: ${{ secrets.SSH_HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        switches: -avz --delete
